const BOOKING_STATUS = {
  PENDING: 'PENDING',
  CONFIRMED: 'CONFIRMED',
  ARRIVING_SOON: 'ARRIVING_SOON',
  ARRIVED: 'ARRIVED',
  SEATED: 'SEATED',
  COMPLETED: 'COMPLETED',
  CANCELLED: 'CANCELLED',
  NO_SHOW: 'NO_SHOW',
};

const TABLE_STATUS = {
  AVAILABLE: 'AVAILABLE',
  RESERVED: 'RESERVED',
  OCCUPIED: 'OCCUPIED',
  CLEANING: 'CLEANING',
  BLOCKED: 'BLOCKED',
};

const BOOKING_SOURCE = {
  WEBSITE: 'WEBSITE',
  PHONE: 'PHONE',
  WALK_IN: 'WALK_IN',
  ADMIN: 'ADMIN',
};

const EVENT_STATUS = {
  NEW: 'NEW',
  CONTACTED: 'CONTACTED',
  QUOTE_SENT: 'QUOTE_SENT',
  CONFIRMED: 'CONFIRMED',
  COMPLETED: 'COMPLETED',
  CANCELLED: 'CANCELLED',
};

module.exports = {
  BOOKING_STATUS,
  TABLE_STATUS,
  BOOKING_SOURCE,
  EVENT_STATUS
};
